### ISSUE TITLE
Change the if blocks in __init__() and predict to assest statements

### ISSUE THREAD

**Issue by Pranav-Rastogi** [Pranav-Rastogi/k_medoids#2]
Inside the K_medoids class, the first function `__init__()` and the last function `predict()` have one `if` statement each. These if conditions need to be changed to assert statements. The text which the errors thrown by the if conditions show can be used for the assert conditions as well.

**Comment by lukaszgard** [comment]
Hi @Pranav-Rastogi  can You assign me to this task ?

**Comment by Pranav-Rastogi** [comment]
This issue has been solved now by @lukaszgard and hence stands closed.
